### ISSUE TITLE
[Feature suggestion] insert users if not exists as optional

### ISSUE THREAD

**Issue by joubertredrat** [kanboard/plugin-google-auth#1]
Hi guys,

I liked this plugin a lot, but I have a suggestion. I think that is good idea to have option to allow Kanboard insert remote user if account doesn't exists. This is good if you have big team, then Kanboard automatic insert remote users if is first login.

What you think? If you like, saw that I develop this feature here.

**Comment by fguillot** [comment]
This is available in the development branch: https://github.com/kanboard/plugin-google-auth#automatic-account-creation
