### ISSUE TITLE
I need help plugin is not working

### ISSUE THREAD

**Issue by rodrigofsantos** [kanboard/plugin-google-auth#5]
I installed the plugin but it has the following error:
400. That's an error.

Error: invalid_request

Device_id and device_name are required for private IP: http://192.168.30.240/kanboard/?controller=OAuthController&amp;action=handler&amp;plugin=GoogleAuth

learn more
That's all we know.

Here I will not use external ip only invalid ip as I solve this

**Comment by fguillot** [comment]
Google do not allow you to use a private IP with OAuth2 authentication. You should use a public domain.

Googling on the net, will give you more information: http://stackoverflow.com/questions/24736168/error-invalid-request-device-id-and-device-name-are-required-for-private-ip
