### ISSUE TITLE
1.0.4 seems to break login

### ISSUE THREAD

**Issue by dhornford** [kanboard/plugin-google-auth#6]
Login page loses formatting, with username & password boxes in top left.
Login fails without any notice, simply a return to login

Application version: 1.0.36
PHP version: 7.0.14
PHP SAPI: apache2handler
OS version: Linux 3.10.0-514.6.1.el7.x86_64
Database driver: mysql
Database version: 5.7.16-log
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by fguillot** [comment]
v1.0.4 require at least Kanboard 1.0.37 to work properly.
