### ISSUE TITLE
Error with configuration.php file

### ISSUE THREAD

**Issue by fgauttron** [kanboard/plugin-google-auth#8]
Hello,

when i configure this plugin with configuration.php file, i have this error

My configuration file look like this 
// Google client id (Get this value from the Google developer console)
define('GOOGLE_CLIENT_ID', 'XXXXXXXX-yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.apps.googleusercontent.com');

// Google client secret key (Get this value from the Google developer console)
define('GOOGLE_CLIENT_SECRET', 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzz');

![error-plugin-kanboard](https://cloud.githubusercontent.com/assets/6348176/25840550/87baffae-349c-11e7-978a-4015fe311d19.jpg)

**Comment by fguillot** [comment]
You should make sure the generated redirect url in Kanboard and the one in the Google console are the same.

**Comment by fgauttron** [comment]
Yes i have the same url in Kanboard and in Google console. It works when i use the configuration with the control pannel instead the configuration file. But i want to configure the sending mail with smtp, So I have to use the config file with the smtp server settings and those of authentication with google.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
