### ISSUE TITLE
Token expiration is quite small

### ISSUE THREAD

**Issue by oliviermaridat** [kanboard/plugin-google-auth#9]
Hi!

I am using this Google Authentication plugin and it is quite useful. However, I need to login again very often, maybe due to OAuth token expiration. Do you have the same behavior?
Is there a way to increase the token expiration delay or use "OAuth refresh token" mechanism?

Thanks!

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
